Optimized for readability
ZeTioZ/ZeFreeze pull request #2
Opened 2024-10-21 20:35 UTC by Mcbencrafter

Hey, i just found your plugin on spigotmc. Its really nice you made it open source!

I changed some stuff to make it more readable including:

- early returning out of a function (https://stackoverflow.com/questions/355670/is-returning-early-from-a-function-more-elegant-than-an-if-statement)
- splitting code in multiple functions instead of having one big one
- not using one letter variables
- formatting the code in the right way (IntelliJ can do this for you using STRG+ALT+L)
- using the java stream api

Hope i could help you a bit :)

Btw i could not test the plugin because some utils were missing and the maven repo was down so you should proprably do this

2024-10-22 15:38 UTC, ZeTioZ commented
Hi, fixed the dependency url so you can test it out ^^

2024-10-29 22:49 UTC, ZeTioZ commented on src/fr/zetioz/zefreeze/FreezeElement.java
Looks pretty much useless to rename the file/object and removing it from it's package seems not to be a good idea either.

2024-10-29 22:53 UTC, ZeTioZ commented on src/fr/zetioz/zefreeze/ZeFreezePlugin.java
Once more, renaming this file is pretty much useless and doesn't add any readability to the code.

2024-10-29 22:55 UTC, ZeTioZ commented on src/fr/zetioz/zefreeze/commands/ZeFreezeCommand.java
It's ok to make them into separate functions, but to really refactor this, we should use the command pattern instead.

2024-10-29 22:59 UTC, ZeTioZ commented on src/fr/zetioz/zefreeze/guis/AntiDisconnectionGUI.java
As it is an homogenous content that will always be a GUI. The package name should stay in the plural form.

2024-10-29 23:03 UTC, ZeTioZ commented on src/fr/zetioz/zefreeze/listener/ZeFreezeBlockBreakListener.java
The file name is correctly changed, but the package name should be in the plural form as they are all instances of events listeners which makes it a homogenous package.

https://www.reddit.com/r/java/comments/1e4ug8/should_package_name_be_plural_or_singular/

2024-10-29 23:05 UTC, ZeTioZ requested changes
Check at files comments

2024-10-30 10:08 UTC, Mcbencrafter commented on src/fr/zetioz/zefreeze/FreezeElement.java
Freeze is not a good name for the class because it says nothing about its purpose, suffixing it with element adds clarity and lets the reader know it doesnt represent a function like freezing the player

2024-10-30 10:09 UTC, Mcbencrafter commented on src/fr/zetioz/zefreeze/FreezeElement.java
And naming the package object also says nothing about its contents. You could name it element, but because its only one class, you can also put it in the root package

2024-10-30 10:10 UTC, Mcbencrafter commented on src/fr/zetioz/zefreeze/ZeFreezePlugin.java
I totally agree, this change isnt that necesarry

2024-10-30 10:27 UTC, Mcbencrafter commented on src/fr/zetioz/zefreeze/guis/AntiDisconnectionGUI.java
As per java naming convention, you should use the singular form as the package name

2024-10-30 10:43 UTC, ZeTioZ commented on src/fr/zetioz/zefreeze/guis/AntiDisconnectionGUI.java
> As per java naming convention, you should use the singular form as the package name

There is no such convention. It's totally up to the dev to make it plural or not. Although there's a consensus to say that it should be plural if extending a class to multiple implementations, otherwise it should be singular. This consensus particularly comes by looking at the JDK that also use it in that way.

2024-11-02 14:47 UTC, ZeTioZ approved these changes

2024-11-02 14:48 UTC, merged